apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronejob-docker-registry
  namespace: docker-registry
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronejob-docker-registry
              image: registry:2.6.2
              imagePullPolicy: IfNotPresent
              env:
                - name: REGISTRY_REDIS_ADDR
                  value: "$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)"
                - name: REGISTRY_REDIS_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: redis-access
                      key: redis-pass
              command:
                - /bin/registry
                - garbage-collect
                - /config.yml
              volumeMounts:
                - name: image-store
                  mountPath: /var/lib/registry
                - name: config-volume
                  mountPath: /config.yml
                  subPath: config.yml
          restartPolicy: OnFailure
          volumes:
            - name: image-store
              persistentVolumeClaim:
                claimName: pvc
            - name: config-volume
              configMap:
                name: docker-registry-garbage-configfile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-garbage-configfile
  namespace: docker-registry
data:
  config.yml: |
    version: 0.1
    storage:
      cache:
          blobdescriptor: redis
      filesystem:
          rootdirectory: /var/lib/registry
      delete:
          enabled: true
      maintenance:
        readonly:
          enabled: true
    redis:
    addr: $(REGISTRY_REDIS_ADDR)
    password: $(REGISTRY_REDIS_PASSWORD)
    db: 0
    dialtimeout: 10ms
    readtimeout: 10ms
    writetimeout: 10ms
    pool:
      maxidle: 16
      maxactive: 64
      idletimeout: 300s
